server:
  port: 8002
spring:
  application:
    name: easybuy-product #不要使用下划线
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easybuy_product
    username: admin
    password: admin
mybatis-plus:
  mapper-locations: classpath:cn/itsource/easybuy/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.easybuy.domain,cn.itsource.easybuy.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka   #告诉服务提供者要把服务注册到哪儿，这是单机版配置一个注册中心
  instance:
    prefer-ip-address: true #表示在注册中心绑定服务后显示服务提供方的真实ip