server:
  port: 9527
spring:
  application:
    name: easybuy-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: easybuy-plat #配置的服务
    plat.path: /plat/**  #以/plat/开头的所有路径都转发给easybuy-plat
    product.serviceId: easybuy-product #配置的服务
    product.path: /product/**  #以/product/开头的所有路径都转发给easybuy-product
  ignored-services:  "*" #可以一个一个配置,但是很麻烦,用*来通配
  prefix: "/services" #加上统一前缀